import React, { useEffect, useMemo, useState } from 'react';

const GRAPH_LIKE_TYPES = new Set([
  'FLOWCHART',
  'GRAPH',
  'TREE',
  'STATE_MACHINE',
  'STEP_PROCESS',
  'ALGORITHM',
  'DECISION_DIAGRAM',
  'RECURSION_TREE',
  'SYSTEM_ARCHITECTURE',
]);

const DIAGRAM_LABELS = {
  FLOWCHART: 'Flowchart',
  GRAPH: 'Graph',
  TREE: 'Tree',
  STATE_MACHINE: 'State Machine',
  STEP_PROCESS: 'Step-by-step Process',
  ALGORITHM: 'Algorithm Visualization',
  TIMELINE: 'Timeline',
  DECISION_DIAGRAM: 'Decision Diagram',
  DP_TABLE: 'DP Table',
  RECURSION_TREE: 'Recursion Tree',
  SYSTEM_ARCHITECTURE: 'System Architecture',
};

const DEFAULT_SANDBOX_CODE = `const { input, helpers } = context;

const nodes = Array.isArray(input.nodes) && input.nodes.length > 0
  ? input.nodes
  : ['A', 'B', 'C', 'D', 'E'];

const edgeList = Array.isArray(input.edges) && input.edges.length > 0
  ? input.edges
  : [
      { from: 'A', to: 'B', weight: 4 },
      { from: 'A', to: 'C', weight: 2 },
      { from: 'C', to: 'B', weight: 1 },
      { from: 'B', to: 'D', weight: 5 },
      { from: 'C', to: 'D', weight: 8 },
      { from: 'C', to: 'E', weight: 10 },
      { from: 'D', to: 'E', weight: 2 },
    ];

const start = input.start || nodes[0];
const target = input.target || nodes[nodes.length - 1];

const adjacency = new Map();
nodes.forEach((node) => adjacency.set(node, []));
edgeList.forEach((edge) => {
  if (!adjacency.has(edge.from)) adjacency.set(edge.from, []);
  adjacency.get(edge.from).push(edge);
});

const dist = {};
const prev = {};
const visited = new Set();
nodes.forEach((node) => {
  dist[node] = Infinity;
  prev[node] = null;
});
dist[start] = 0;

const steps = [];
steps.push({
  title: 'Initialize Distances',
  explanation: 'Set all distances to Infinity except the start node.',
  activeNodes: [start],
  activeEdges: [],
  stateValues: {
    start,
    target,
    distances: { ...dist },
    visited: [],
  },
});

while (visited.size < nodes.length) {
  let current = null;
  let bestDistance = Infinity;

  nodes.forEach((node) => {
    if (!visited.has(node) && dist[node] < bestDistance) {
      bestDistance = dist[node];
      current = node;
    }
  });

  if (!current || bestDistance === Infinity) break;
  visited.add(current);

  steps.push({
    title: 'Visit ' + current,
    explanation: 'Select the unvisited node with the smallest tentative distance.',
    activeNodes: [current],
    activeEdges: [],
    stateValues: {
      current,
      distance: dist[current],
      visited: [...visited],
      distances: { ...dist },
    },
  });

  const neighbors = adjacency.get(current) || [];
  neighbors.forEach((edge) => {
    const nextDistance = dist[current] + (edge.weight || 0);
    if (nextDistance < (dist[edge.to] ?? Infinity)) {
      dist[edge.to] = nextDistance;
      prev[edge.to] = current;
      steps.push({
        title: 'Relax ' + edge.from + ' -> ' + edge.to,
        explanation: 'Found a shorter path to ' + edge.to + '.',
        activeNodes: [current, edge.to],
        activeEdges: [helpers.edgeId(edge.from, edge.to)],
        stateValues: {
          updatedNode: edge.to,
          newDistance: nextDistance,
          predecessor: current,
          distances: { ...dist },
        },
      });
    }
  });

  if (current === target) break;
}

const path = [];
let pointer = target;
while (pointer) {
  path.unshift(pointer);
  pointer = prev[pointer];
}

const pathEdgeIds = [];
for (let i = 0; i < path.length - 1; i += 1) {
  pathEdgeIds.push(helpers.edgeId(path[i], path[i + 1]));
}

if (path.length > 0 && path[0] === start) {
  steps.push({
    title: 'Reconstruct Path',
    explanation: 'Backtrack predecessors to build the shortest path.',
    activeNodes: path,
    activeEdges: pathEdgeIds,
    stateValues: {
      path,
      totalCost: dist[target],
    },
  });
}

return {
  title: 'Programmable Dijkstra Sandbox',
  diagramType: 'GRAPH',
  description: 'Generated by sandbox code. Edit input or script to simulate other processes.',
  hint: 'You can return any simulation object shape from this script.',
  solutionText:
    path.length > 0 && path[0] === start
      ? 'Shortest path: ' + path.join(' -> ') + ' (cost ' + dist[target] + ')'
      : 'No path found from ' + start + ' to ' + target + '.',
  nodes: nodes.map((id) => ({ id, label: id })),
  edges: edgeList.map((edge) => ({
    id: helpers.edgeId(edge.from, edge.to),
    from: edge.from,
    to: edge.to,
    label: typeof edge.weight === 'number' ? String(edge.weight) : '',
  })),
  steps,
};`;

const fallbackSimulation = {
  title: 'Interactive Simulation Sandbox',
  diagramType: 'GRAPH',
  description: 'Run this sandbox to generate interactive steps and visuals.',
  hint: 'Edit code and input in Lesson Editor to simulate any process.',
  nodes: [],
  edges: [],
  steps: [
    {
      title: 'Waiting for Program',
      explanation: 'Enable sandbox mode and run a simulation script.',
      activeNodes: [],
      activeEdges: [],
      stateValues: {},
    },
  ],
  solutionText: 'Program output appears after running sandbox code.',
  sandbox: {
    enabled: true,
    code: DEFAULT_SANDBOX_CODE,
    inputJson: JSON.stringify(
      {
        start: 'A',
        target: 'E',
        nodes: ['A', 'B', 'C', 'D', 'E'],
        edges: [
          { from: 'A', to: 'B', weight: 4 },
          { from: 'A', to: 'C', weight: 2 },
          { from: 'C', to: 'B', weight: 1 },
          { from: 'B', to: 'D', weight: 5 },
          { from: 'C', to: 'D', weight: 8 },
          { from: 'C', to: 'E', weight: 10 },
          { from: 'D', to: 'E', weight: 2 },
        ],
      },
      null,
      2
    ),
  },
};

const isPlainObject = (value) => value && typeof value === 'object' && !Array.isArray(value);

const asArray = (value) => (Array.isArray(value) ? value : []);

const parseMaybeJson = (value) => {
  if (isPlainObject(value) || Array.isArray(value)) {
    return { value, error: '' };
  }
  if (typeof value !== 'string' || value.trim() === '') {
    return { value: {}, error: '' };
  }
  try {
    return { value: JSON.parse(value), error: '' };
  } catch (error) {
    return { value: {}, error: error.message };
  }
};

const safeParseSimulation = (content) => {
  if (!content) return { ...fallbackSimulation };

  if (isPlainObject(content)) {
    return {
      ...fallbackSimulation,
      ...content,
      sandbox: {
        ...fallbackSimulation.sandbox,
        ...(isPlainObject(content.sandbox) ? content.sandbox : {}),
      },
    };
  }

  if (typeof content === 'string') {
    try {
      const parsed = JSON.parse(content);
      if (!isPlainObject(parsed)) return { ...fallbackSimulation };
      return {
        ...fallbackSimulation,
        ...parsed,
        sandbox: {
          ...fallbackSimulation.sandbox,
          ...(isPlainObject(parsed.sandbox) ? parsed.sandbox : {}),
        },
      };
    } catch (error) {
      return { ...fallbackSimulation };
    }
  }

  return { ...fallbackSimulation };
};

const edgeId = (edge) => edge.id || `${edge.from}->${edge.to}`;

const renderStateValue = (value) => {
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
};

const buildSandboxHelpers = () => ({
  range: (start, end, step = 1) => {
    let from = start;
    let to = end;
    if (end === undefined) {
      from = 0;
      to = start;
    }
    if (step === 0) return [];
    const values = [];
    if (from <= to) {
      for (let i = from; i < to; i += Math.abs(step)) values.push(i);
    } else {
      for (let i = from; i > to; i -= Math.abs(step)) values.push(i);
    }
    return values;
  },
  edgeId: (from, to) => `${from}->${to}`,
  clone: (value) => JSON.parse(JSON.stringify(value)),
  step: (data) => ({
    title: data?.title || 'Step',
    explanation: data?.explanation || '',
    activeNodes: asArray(data?.activeNodes),
    activeEdges: asArray(data?.activeEdges),
    stateValues: isPlainObject(data?.stateValues) ? data.stateValues : {},
    highlightCells: asArray(data?.highlightCells),
    timelineIndex: typeof data?.timelineIndex === 'number' ? data.timelineIndex : undefined,
  }),
});

const normalizeGeneratedSimulation = (baseSimulation, generated) => {
  if (!isPlainObject(generated)) return baseSimulation;
  return {
    ...baseSimulation,
    ...generated,
    nodes: asArray(generated.nodes),
    edges: asArray(generated.edges),
    steps: asArray(generated.steps),
    timeline: asArray(generated.timeline),
    table: asArray(generated.table),
    sandbox: baseSimulation.sandbox,
  };
};

const executeSandboxProgram = (simulation, runKey) => {
  const sandbox = simulation.sandbox || {};

  if (!sandbox.enabled) {
    return {
      simulation,
      scriptError: '',
      inputError: '',
      isProgrammed: false,
    };
  }

  const script = (sandbox.code || '').trim();
  if (!script) {
    return {
      simulation,
      scriptError: 'Sandbox is enabled, but script code is empty.',
      inputError: '',
      isProgrammed: false,
    };
  }

  const parsedInput = parseMaybeJson(
    typeof sandbox.inputJson === 'string' ? sandbox.inputJson : sandbox.inputJson || sandbox.input || '{}'
  );

  if (parsedInput.error) {
    return {
      simulation,
      scriptError: '',
      inputError: `Sandbox input JSON is invalid: ${parsedInput.error}`,
      isProgrammed: false,
    };
  }

  try {
    const evaluator = new Function(
      'context',
      `
        "use strict";
        const window = undefined;
        const document = undefined;
        const globalThis = undefined;
        const fetch = undefined;
        const XMLHttpRequest = undefined;
        const WebSocket = undefined;
        const localStorage = undefined;
        const sessionStorage = undefined;
        const process = undefined;
        const require = undefined;
        const Function = undefined;
        ${script}
      `
    );

    const context = Object.freeze({
      input: parsedInput.value,
      helpers: buildSandboxHelpers(),
      meta: Object.freeze({
        title: simulation.title,
        diagramType: simulation.diagramType,
        runKey,
      }),
    });

    const generated = evaluator(context);
    const merged = normalizeGeneratedSimulation(simulation, generated);

    if (!isPlainObject(generated)) {
      return {
        simulation,
        scriptError: 'Sandbox code must return a simulation object.',
        inputError: '',
        isProgrammed: false,
      };
    }

    return {
      simulation: merged,
      scriptError: '',
      inputError: '',
      isProgrammed: true,
    };
  } catch (error) {
    return {
      simulation,
      scriptError: `Sandbox runtime error: ${error.message}`,
      inputError: '',
      isProgrammed: false,
    };
  }
};

function GraphCanvas({ simulation, activeStep, compact }) {
  const nodes = asArray(simulation.nodes);
  const edges = asArray(simulation.edges);

  const activeNodeIds = new Set(asArray(activeStep?.activeNodes));
  const activeEdgeIds = new Set(asArray(activeStep?.activeEdges));
  const shouldDim = activeNodeIds.size > 0;

  return (
    <div className="space-y-4">
      <div className={`grid grid-cols-1 sm:grid-cols-2 ${compact ? 'lg:grid-cols-2' : 'lg:grid-cols-3'} gap-3`}>
        {nodes.map((node) => {
          const isActive = activeNodeIds.has(node.id);
          const isDimmed = shouldDim && !isActive;
          return (
            <div
              key={node.id}
              className={`rounded-xl border px-3 py-2 transition-all duration-300 ${
                isActive
                  ? 'border-primary bg-primary/10 shadow-sm scale-[1.01]'
                  : isDimmed
                    ? 'border-outline-variant/20 bg-surface-container-low opacity-45'
                    : 'border-outline-variant/30 bg-surface-container-lowest'
              }`}
            >
              <p className="text-xs font-bold text-outline uppercase tracking-widest">{node.id}</p>
              <p className="text-sm font-semibold text-on-surface mt-1">{node.label || node.id}</p>
            </div>
          );
        })}
      </div>

      {edges.length > 0 && (
        <div className="space-y-2">
          <p className="text-[10px] font-bold uppercase tracking-widest text-outline">Transitions</p>
          {edges.map((edge) => {
            const currentEdgeId = edgeId(edge);
            const reverseEdgeId = `${edge.to}->${edge.from}`;
            const isActive = activeEdgeIds.has(currentEdgeId) || activeEdgeIds.has(reverseEdgeId);
            const isDimmed = activeEdgeIds.size > 0 && !isActive;
            return (
              <div
                key={currentEdgeId}
                className={`rounded-lg px-3 py-2 border text-xs transition-all duration-300 ${
                  isActive
                    ? 'border-primary/40 bg-primary/10 text-primary font-semibold'
                    : isDimmed
                      ? 'border-outline-variant/20 bg-surface-container-low opacity-40'
                      : 'border-outline-variant/30 bg-surface-container-lowest text-outline'
                }`}
              >
                {edge.from} {'->'} {edge.to}
                {edge.label ? <span className="ml-2">({edge.label})</span> : null}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

function TimelineCanvas({ simulation, activeStep }) {
  const timelineItems = asArray(simulation.timeline).length
    ? asArray(simulation.timeline)
    : asArray(simulation.steps).map((step, index) => ({
        id: `step-${index + 1}`,
        label: step.title || `Step ${index + 1}`,
      }));
  const activeIndex = typeof activeStep?.timelineIndex === 'number' ? activeStep.timelineIndex : 0;

  return (
    <div className="space-y-2">
      <div className="flex flex-wrap gap-3">
        {timelineItems.map((item, index) => {
          const isActive = index === activeIndex;
          const isPassed = index < activeIndex;
          return (
            <div key={item.id || index} className="flex items-center gap-2">
              <div
                className={`w-7 h-7 rounded-full text-xs font-bold flex items-center justify-center transition-all duration-300 ${
                  isActive
                    ? 'bg-primary text-white scale-110'
                    : isPassed
                      ? 'bg-secondary text-white'
                      : 'bg-surface-container-high text-outline'
                }`}
              >
                {index + 1}
              </div>
              <p className={`text-sm ${isActive ? 'font-bold text-on-surface' : 'text-outline'}`}>
                {item.label || `Step ${index + 1}`}
              </p>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function TableCanvas({ simulation, activeStep }) {
  const table = asArray(simulation.table);
  const highlighted = new Set(asArray(activeStep?.highlightCells).map((cell) => `${cell.row}-${cell.col}`));

  if (table.length === 0) {
    return (
      <div className="rounded-xl border border-outline-variant/20 p-4 text-sm text-outline bg-surface-container-low">
        Add table rows in simulation data to render DP/state tables.
      </div>
    );
  }

  return (
    <div className="overflow-x-auto">
      <table className="min-w-full border-collapse">
        <tbody>
          {table.map((row, rowIndex) => (
            <tr key={`row-${rowIndex}`}>
              {asArray(row).map((cell, colIndex) => {
                const key = `${rowIndex}-${colIndex}`;
                const isHighlighted = highlighted.has(key);
                return (
                  <td
                    key={key}
                    className={`border px-3 py-2 text-sm transition-all duration-300 ${
                      isHighlighted
                        ? 'bg-primary/10 border-primary/40 text-primary font-semibold'
                        : 'border-outline-variant/30 bg-surface-container-lowest text-on-surface'
                    }`}
                  >
                    {renderStateValue(cell)}
                  </td>
                );
              })}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default function InteractiveSimulationBlock({ block, compact = false }) {
  const baseSimulation = useMemo(() => safeParseSimulation(block?.content), [block?.content]);
  const [runKey, setRunKey] = useState(0);

  const runtime = useMemo(
    () => executeSandboxProgram(baseSimulation, runKey),
    [baseSimulation, runKey]
  );

  const simulation = runtime.simulation;
  const steps = asArray(simulation.steps);
  const diagramType = simulation.diagramType || 'FLOWCHART';

  const [currentStep, setCurrentStep] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [speed, setSpeed] = useState(1);
  const [showSolution, setShowSolution] = useState(false);
  const [stepMode, setStepMode] = useState(true);
  const [showHint, setShowHint] = useState(false);

  useEffect(() => {
    setCurrentStep(0);
    setIsPlaying(false);
    setShowSolution(false);
  }, [block?.id, block?.localId, block?.content, runKey]);

  useEffect(() => {
    if (!isPlaying) return undefined;
    if (steps.length <= 1) return undefined;

    const intervalMs = Math.max(250, Math.round(1200 / speed));
    const timer = setInterval(() => {
      setCurrentStep((previous) => {
        if (previous >= steps.length - 1) {
          setIsPlaying(false);
          return previous;
        }
        return previous + 1;
      });
    }, intervalMs);

    return () => clearInterval(timer);
  }, [isPlaying, speed, steps.length]);

  const activeStep = steps[currentStep] || {};
  const totalSteps = Math.max(steps.length, 1);
  const isSandboxEnabled = Boolean(baseSimulation?.sandbox?.enabled);

  const goStepBack = () => {
    setShowSolution(false);
    setCurrentStep((previous) => Math.max(previous - 1, 0));
  };

  const goStepForward = () => {
    setShowSolution(false);
    setCurrentStep((previous) => Math.min(previous + 1, totalSteps - 1));
  };

  const resetSimulation = () => {
    setIsPlaying(false);
    setShowSolution(false);
    setCurrentStep(0);
  };

  const startAutoPlay = () => {
    if (stepMode) return;
    setShowSolution(false);
    setIsPlaying(true);
  };

  const toggleStepMode = () => {
    setStepMode((previous) => {
      const next = !previous;
      if (next) setIsPlaying(false);
      return next;
    });
  };

  const renderDiagram = () => {
    if (diagramType === 'TIMELINE') {
      return <TimelineCanvas simulation={simulation} activeStep={activeStep} />;
    }
    if (diagramType === 'DP_TABLE') {
      return <TableCanvas simulation={simulation} activeStep={activeStep} />;
    }
    if (GRAPH_LIKE_TYPES.has(diagramType)) {
      return <GraphCanvas simulation={simulation} activeStep={activeStep} compact={compact} />;
    }
    return <GraphCanvas simulation={simulation} activeStep={activeStep} compact={compact} />;
  };

  return (
    <article className={`rounded-2xl border border-outline-variant/20 bg-surface-container-lowest p-5 md:p-6 shadow-sm ${compact ? '' : 'space-y-5'}`}>
      <header className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="text-xs font-bold uppercase tracking-widest text-primary flex items-center gap-1">
            <span className="material-symbols-outlined text-sm">experiment</span>
            Interactive Simulation
          </p>
          <h3 className="text-xl font-bold text-on-surface mt-1">{simulation.title || 'Simulation Block'}</h3>
          <div className="flex flex-wrap items-center gap-2 mt-1">
            <p className="text-[11px] font-semibold text-outline uppercase tracking-wider">
              {DIAGRAM_LABELS[diagramType] || diagramType}
            </p>
            {isSandboxEnabled && (
              <span className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full ${runtime.isProgrammed ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>
                Sandbox
              </span>
            )}
          </div>
        </div>
        <div className="text-xs font-semibold text-outline bg-surface-container-low px-3 py-1 rounded-full">
          Step {Math.min(currentStep + 1, totalSteps)} / {totalSteps}
        </div>
      </header>

      {runtime.inputError && (
        <div className="rounded-xl border border-amber-400/40 bg-amber-50 px-4 py-3 text-sm text-amber-800">
          {runtime.inputError}
        </div>
      )}

      {runtime.scriptError && (
        <div className="rounded-xl border border-error/30 bg-error-container/40 px-4 py-3 text-sm text-on-surface">
          {runtime.scriptError}
        </div>
      )}

      <div className="flex flex-wrap gap-2">
        <button type="button" onClick={goStepBack} className="px-3 py-1.5 rounded-lg border border-outline-variant/30 text-xs font-bold hover:bg-surface-container-low transition-colors">
          Step Back
        </button>
        <button type="button" onClick={goStepForward} className="px-3 py-1.5 rounded-lg border border-outline-variant/30 text-xs font-bold hover:bg-surface-container-low transition-colors">
          Step Forward
        </button>
        <button
          type="button"
          onClick={startAutoPlay}
          disabled={stepMode}
          className="px-3 py-1.5 rounded-lg border border-outline-variant/30 text-xs font-bold hover:bg-surface-container-low transition-colors disabled:opacity-40"
        >
          Auto Play
        </button>
        <button type="button" onClick={() => setIsPlaying(false)} className="px-3 py-1.5 rounded-lg border border-outline-variant/30 text-xs font-bold hover:bg-surface-container-low transition-colors">
          Pause
        </button>
        <button type="button" onClick={resetSimulation} className="px-3 py-1.5 rounded-lg border border-outline-variant/30 text-xs font-bold hover:bg-surface-container-low transition-colors">
          Reset
        </button>
        {isSandboxEnabled && (
          <button type="button" onClick={() => setRunKey((previous) => previous + 1)} className="px-3 py-1.5 rounded-lg border border-primary/40 bg-primary/10 text-xs font-bold text-primary hover:bg-primary/15 transition-colors">
            Run Program
          </button>
        )}
        <button
          type="button"
          onClick={() => setShowSolution((previous) => !previous)}
          className={`px-3 py-1.5 rounded-lg border text-xs font-bold transition-colors ${
            showSolution
              ? 'border-secondary/40 bg-secondary/10 text-secondary'
              : 'border-outline-variant/30 hover:bg-surface-container-low'
          }`}
        >
          {showSolution ? 'Hide Solution' : 'Show Solution'}
        </button>
        <button
          type="button"
          onClick={toggleStepMode}
          className={`px-3 py-1.5 rounded-lg border text-xs font-bold transition-colors ${
            stepMode
              ? 'border-primary/40 bg-primary/10 text-primary'
              : 'border-outline-variant/30 hover:bg-surface-container-low'
          }`}
        >
          {stepMode ? 'Step Mode On' : 'Step Mode Off'}
        </button>
        <button
          type="button"
          onClick={() => setShowHint((previous) => !previous)}
          className={`px-3 py-1.5 rounded-lg border text-xs font-bold transition-colors ${
            showHint
              ? 'border-amber-500/40 bg-amber-500/10 text-amber-700'
              : 'border-outline-variant/30 hover:bg-surface-container-low'
          }`}
        >
          {showHint ? 'Hide Hint' : 'Hint'}
        </button>
      </div>

      <div className="rounded-xl border border-outline-variant/20 bg-surface p-4 transition-all duration-300">
        {renderDiagram()}
      </div>

      <div className="flex flex-wrap items-center gap-3">
        <label className="text-xs font-bold uppercase tracking-widest text-outline">Speed</label>
        <input
          type="range"
          min="0.5"
          max="3"
          step="0.25"
          value={speed}
          onChange={(event) => setSpeed(parseFloat(event.target.value))}
          className="w-36 accent-primary"
        />
        <span className="text-xs font-semibold text-outline">{speed.toFixed(2)}x</span>
      </div>

      {(simulation.description || activeStep.explanation || showSolution || showHint) && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <section className="rounded-xl border border-outline-variant/20 bg-surface-container-low p-4">
            <p className="text-[10px] font-bold uppercase tracking-widest text-outline">Explanation Panel</p>
            <p className="text-sm text-on-surface mt-2 leading-relaxed">
              {showSolution
                ? simulation.solutionText || 'Solution view enabled. Inspect final state values.'
                : activeStep.explanation || simulation.description || 'Step through the simulation to see details.'}
            </p>
            {activeStep.title ? (
              <p className="mt-2 text-xs font-semibold text-primary">Current: {activeStep.title}</p>
            ) : null}
          </section>

          <section className="rounded-xl border border-outline-variant/20 bg-surface-container-low p-4">
            <p className="text-[10px] font-bold uppercase tracking-widest text-outline">Live State Values</p>
            <div className="mt-2 space-y-1">
              {Object.entries(activeStep.stateValues || {}).length === 0 ? (
                <p className="text-sm text-outline italic">No live values on this step.</p>
              ) : (
                Object.entries(activeStep.stateValues || {}).map(([key, value]) => (
                  <p key={key} className="text-sm text-on-surface">
                    <span className="font-bold">{key}:</span> {renderStateValue(value)}
                  </p>
                ))
              )}
            </div>
          </section>
        </div>
      )}

      {showHint && simulation.hint && (
        <div className="rounded-xl border border-amber-500/30 bg-amber-50 px-4 py-3 text-sm text-amber-800">
          <p className="font-semibold">Hint:</p>
          <p className="mt-1">{simulation.hint}</p>
        </div>
      )}

      {steps.length > 0 && (
        <div className="space-y-2">
          <p className="text-[10px] font-bold uppercase tracking-widest text-outline">Step Trail</p>
          <div className="flex flex-wrap gap-2">
            {steps.map((step, index) => (
              <button
                key={`${step.title || 'step'}-${index}`}
                type="button"
                onClick={() => {
                  setShowSolution(false);
                  setCurrentStep(index);
                }}
                className={`px-2.5 py-1 rounded-full text-xs border transition-all duration-300 ${
                  index === currentStep
                    ? 'border-primary bg-primary/10 text-primary font-bold'
                    : 'border-outline-variant/30 text-outline hover:bg-surface-container-low'
                }`}
              >
                {index + 1}. {step.title || `Step ${index + 1}`}
              </button>
            ))}
          </div>
        </div>
      )}
    </article>
  );
}
